In [3]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib
from ydata_profiling import ProfileReport
import os
print(os.getcwd())

/home/jovyan/code/notebooks


In [4]:
df = pd.read_csv("train.csv")


In [6]:
imu_cols_acceleration = [column for column in df.columns if column.startswith("acc_")]

print(df[imu_cols_acceleration].values)

[[ 6.68359375  6.21484375  3.35546875]
 [ 6.94921875  6.21484375  3.125     ]
 [ 5.72265625  5.41015625  5.421875  ]
 ...
 [ 3.08203125  0.21875    -7.40234375]
 [ 3.96484375 -0.359375   -9.0859375 ]
 [ 4.26953125 -0.93359375 -9.62890625]]


In [7]:
df[imu_cols_acceleration].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 574945 entries, 0 to 574944
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   acc_x   574945 non-null  float64
 1   acc_y   574945 non-null  float64
 2   acc_z   574945 non-null  float64
dtypes: float64(3)
memory usage: 13.2 MB


In [8]:
#If see if there is any None
df[imu_cols_acceleration][df[imu_cols_acceleration].isnull().any(axis=1)]

Empty DataFrame
Columns: [acc_x, acc_y, acc_z]
Index: []

In [9]:
#To see if there is any Duplicated
df.loc[df.duplicated(), imu_cols_acceleration]

Empty DataFrame
Columns: [acc_x, acc_y, acc_z]
Index: []

In [10]:
profile_acc = ProfileReport(df[imu_cols_acceleration], title="Data Quality in acceleration", explorative=True)
profile_acc.to_file("data_quality_acceleration.html")

/opt/conda/lib/python3.12/site-packages/ydata_profiling/utils/dataframe.py:137: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 3/3 [00:00<00:00, 12.97it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [6]:
imu_cols_rotation = [columns for columns in df.columns if columns.startswith("rot_")]
print(imu_cols_rotation)

['rot_w', 'rot_x', 'rot_y', 'rot_z']


In [14]:
profile_rot = ProfileReport(df[imu_cols_rotation], title="Data Quality in rotation", explorative= True)
profile_rot.to_file("data_quality_rotation.html")

/opt/conda/lib/python3.12/site-packages/ydata_profiling/utils/dataframe.py:137: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)


Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]


100%|██████████| 4/4 [00:00<00:00,  5.79it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df[imu_cols_rotation][df[imu_cols_rotation].isnull().any(axis=1)]

rot_w  rot_x  rot_y  rot_z
11110     NaN    NaN    NaN    NaN
11111     NaN    NaN    NaN    NaN
11112     NaN    NaN    NaN    NaN
11113     NaN    NaN    NaN    NaN
11114     NaN    NaN    NaN    NaN
...       ...    ...    ...    ...
559841    NaN    NaN    NaN    NaN
559842    NaN    NaN    NaN    NaN
559843    NaN    NaN    NaN    NaN
559844    NaN    NaN    NaN    NaN
559845    NaN    NaN    NaN    NaN

[3692 rows x 4 columns]